
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpttfzjneoiehctwuzcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwdHRmempuZW9pZWhjdHd1emNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODQxMDcsImV4cCI6MjA1OTg2MDEwN30.QwSi0BcsK_Fhch2upqrOfmeXVr11-_a9TT0w-ZWJFvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Criar bucket para imagens de cursos
(async () => {
  const { data, error } = await supabase.storage.getBucket('course-images');
  if (error && error.code === '404') {
    // Bucket não existe, vamos criar
    await supabase.storage.createBucket('course-images', {
      public: true,
      fileSizeLimit: 1024 * 1024 * 5 // 5MB
    });
  }
})();
